### ISSUE TITLE
Oil window up; goto other window, open or edit; close all other windows, folowed by _s

### ISSUE THREAD

**Issue by Callophrys** [JustBarnt/JustNvim#11]
This happens when trying to remove the oil window.

 * seems avoidable by opening desired file first in oil, then ctrl-l or h to get into oil and :q the oil window

`Error detected while processing WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..FileType Autocommands for "*":                                                                                                                         E218: Autocommand nesting too deep                                                                                                                  Error detected while processing WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*"..WinNew Autocommands for "*":                                                                                                                           Error executing lua callback: ...l/nvim-data/lazy/nvim-notify/lua/notify/service/init.lua:51: Vim:E218: Autocommand nesting too deep                stack traceback:                                                                                                                                            [C]: in function 'nvim_create_buf'                                                                                                                  ...l/nvim-data/lazy/nvim-notify/lua/notify/service/init.lua:51: in function 'push'                                                                  ...Local/nvim-data/lazy/nvim-notify/lua/notify/instance.lua:77: in function 'notify'                                                                ...t/AppData/Local/nvim-data/lazy/oil.nvim/lua/oil/init.lua:1156: in function <...t/AppData/Local/nvim-data/lazy/oil.nvim/lua/oil/init.lua:1137>                                                                                                                                                        [C]: in function 'nvim_open_win'                                                                                                                    ...ocal/nvim-data/lazy/nvim-notify/lua/notify/util/init.lua:78: in function 'open_win'                                                              ...l/nvim-data/lazy/nvim-notify/lua/notify/windows/init.lua:65: in function 'push_pending'                                                          ...l/nvim-data/lazy/nvim-notify/lua/notify/windows/init.lua:31: in function <...l/nvim-data/lazy/nvim-notify/lua/notify/windows/init.lua:30>                                                                                                                                                            [C]: in function 'pcall'   `

**Comment by JustBarnt** [comment]
Fixed by using Neotree- both oil and edgy seem to fight each other. I've been playing around with Neotree and I can make it work sorta like oil which I'm with
